namespace Verse
{
	public enum ThingRequestGroup : byte
	{
		Undefined = 0,
		Nothing = 1,
		Everything = 2,
		HaulableEver = 3,
		HaulableAlways = 4,
		FoodSource = 5,
		FoodSourceNotPlantOrTree = 6,
		Corpse = 7,
		Blueprint = 8,
		BuildingArtificial = 9,
		BuildingFrame = 10,
		Pawn = 11,
		PotentialBillGiver = 12,
		Medicine = 13,
		Filth = 14,
		AttackTarget = 15,
		Weapon = 16,
		Refuelable = 17,
		HaulableEverOrMinifiable = 18,
		Drug = 19,
		Shell = 20,
		HarvestablePlant = 21,
		Fire = 22,
		Plant = 23,
		Construction = 24,
		HasGUIOverlay = 25,
		Apparel = 26,
		MinifiedThing = 27,
		Grave = 28,
		Art = 29,
		ThingHolder = 30,
		ActiveDropPod = 31,
		Transporter = 32,
		LongRangeMineralScanner = 33,
		AffectsSky = 34,
		PsychicDroneEmanator = 35,
		WindSource = 36,
		AlwaysFlee = 37,
		WildAnimalsFlee = 38
	}
}
